num1 = input ("ingresa un numero:")
num2 = input("ingresa otro numero:")
suma= int(num1) + int(num2)
print("la suma es:" , suma) 
div= int(num1) / int(num2)
print("la divison es:" , div )
multi=int(num1) * int (num2)
print("la multiplicación es:" ,multi)
resta=int(num1) - int(num2)
print("la resta es:" , resta)